/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props: any) {
  const group = useRef();
  const { nodes, materials }: { nodes: any; materials: any } = useGLTF(
    "/models/guitar.gltf"
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        rotation={[-0.2, 0, 0]}
        geometry={nodes.parlourGuitar.geometry}
        material={materials["Parlor-Guitar.MAT"]}
      >
        <mesh
          geometry={nodes.parlourGuitarstringe.geometry}
          material={nodes.parlourGuitarstringe.material}
        />
        <mesh
          geometry={nodes.parlourGuitarstringG.geometry}
          material={nodes.parlourGuitarstringG.material}
        />
        <mesh
          geometry={nodes.parlourGuitarstringA.geometry}
          material={nodes.parlourGuitarstringA.material}
        />
        <mesh
          geometry={nodes.parlourGuitarstringB.geometry}
          material={nodes.parlourGuitarstringB.material}
        />
        <mesh
          geometry={nodes.parlourGuitarstringD.geometry}
          material={nodes.parlourGuitarstringD.material}
        />
        <mesh
          geometry={nodes.parlourGuitarstringE.geometry}
          material={nodes.parlourGuitarstringE.material}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/guitar.gltf");
